In [39]:
!pip install spotipy

Requirement already satisfied: spotipy in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (2.26.0)
Requirement already satisfied: redis>=3.5.3 in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (from spotipy) (7.2.1)
Requirement already satisfied: requests>=2.25.0 in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (from spotipy) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (from spotipy) (2.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.25.0->spotipy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.25.0->spotipy) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\prachi raghuwanshi\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.25.0->spotipy) (2025.1.31)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

In [53]:
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        client_id="bc91b5e2fdfb46b4be9f81c6090e7d93",
        client_secret="12022a438f7646f6a1c2e26e413fd5ca",
        redirect_uri="http://127.0.0.1:8888/callback",
        scope="playlist-read-private"
))

In [54]:
playlist_link = "https://open.spotify.com/playlist/37i9dQZEVXbNG2KDcFcKOF"

In [56]:
playlist_URI = playlist_link.split("/")[-1].split("?")[0]

data = sp.playlist_items(playlist_URI)

PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

In [48]:
playlist_URI = playlist_link.split("/")[-1]
playlist_URI

'37i9dQZF1DXcBWIGoYBM5M'

In [49]:
data = sp.playlist_items(playlist_URI)

HTTP Error for GET to https://api.spotify.com/v1/playlists/37i9dQZF1DXcBWIGoYBM5M/items with Params: {'limit': 50, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track,episode'} returned 401 due to Valid user authentication required

SpotifyException: http status: 401, code: -1 - https://api.spotify.com/v1/playlists/37i9dQZF1DXcBWIGoYBM5M/items?limit=50&offset=0&additional_types=track%2Cepisode:
 Valid user authentication required, reason: None

In [59]:
data['items']

NameError: name 'data' is not defined

In [32]:
data['items'][0]['track']['album']['id']

'7I0tjwFtxUwBC1vgyeMAax'

In [33]:
data['items'][0]['track']['album']['name']

'Flowers'

In [35]:
data['items'][0]['track']['album']['release_date']

'2023-01-13'

In [37]:
data['items'][0]['track']['album']['total_tracks']

1

In [43]:
data['items'][0]['track']['album']['external_urls']['spotify']

'https://open.spotify.com/album/7I0tjwFtxUwBC1vgyeMAax'

In [48]:
album_list = []
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id':album_id,'name':album_name,'release_date':album_release_date,
                        'total_tracks':album_total_tracks,'url':album_url}
    album_list.append(album_element)

In [49]:
album_list

[{'album_id': '7I0tjwFtxUwBC1vgyeMAax',
  'name': 'Flowers',
  'release_date': '2023-01-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7I0tjwFtxUwBC1vgyeMAax'},
 {'album_id': '1nrVofqDRs7cpWXJ49qTnP',
  'name': 'SOS',
  'release_date': '2022-12-08',
  'total_tracks': 23,
  'url': 'https://open.spotify.com/album/1nrVofqDRs7cpWXJ49qTnP'},
 {'album_id': '1gi2iwr1l8IUyHYHxi01pg',
  'name': 'Shakira: Bzrp Music Sessions, Vol. 53',
  'release_date': '2023-01-11',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1gi2iwr1l8IUyHYHxi01pg'},
 {'album_id': '3Uq1jNGnD412ZvCb6j2DKV',
  'name': 'Gloria',
  'release_date': '2023-01-27',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/3Uq1jNGnD412ZvCb6j2DKV'},
 {'album_id': '7txGsnDSqVMoRl6RQ9XyZP',
  'name': 'HEROES & VILLAINS',
  'release_date': '2022-12-02',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/7txGsnDSqVMoRl6RQ9XyZP'},
 {'album_id': '5r36AJ6VOJtp00oxSkBZ5h',
  'name': "Harry's House",
  'release_date': '2022-05-20',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/5r36AJ6VOJtp00oxSkBZ5h'},
 {'album_id': '1TpGeAzOJgAGdPkcWl95r2',
  'name': 'La Bachata',
  'release_date': '2022-05-26',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1TpGeAzOJgAGdPkcWl95r2'},
 {'album_id': '5xefnzEqKIWnmTWYFzekGZ',
  'name': 'Resistencia',
  'release_date': '2023-01-13',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/5xefnzEqKIWnmTWYFzekGZ'},
 {'album_id': '7M842DMhYVALrXsw3ty7B3',
  'name': "I'm Good (Blue)",
  'release_date': '2022-08-26',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/7M842DMhYVALrXsw3ty7B3'},
 {'album_id': '3U8n8LzBx2o9gYXvvNq4uH',
  'name': 'My 21st Century Blues',
  'release_date': '2023-02-03',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/3U8n8LzBx2o9gYXvvNq4uH'},
 {'album_id': '2b2GHWESCWEuHiCZ2Skedp',
  'name': 'Calm Down (with Selena Gomez)',
  'release_date': '2022-08-25',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2b2GHWESCWEuHiCZ2Skedp'},
 {'album_id': '151w1FgRZfnKZA9FEcg9Z3',
  'name': 'Midnights',
  'release_date': '2022-10-21',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/151w1FgRZfnKZA9FEcg9Z3'},
 {'album_id': '4AdZV63ycxFLF6Hcol0QnB',
  'name': 'Starboy',
  'release_date': '2016-11-24',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/4AdZV63ycxFLF6Hcol0QnB'},
 {'album_id': '2AvuFDqTlnxvYhyVaLU6NY',
  'name': 'Sr. Santos',
  'release_date': '2022-12-01',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/2AvuFDqTlnxvYhyVaLU6NY'},
 {'album_id': '0OuoHWf8yB0TPzoBWw1R1S',
  'name': 'Here With Me',
  'release_date': '2022-09-22',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0OuoHWf8yB0TPzoBWw1R1S'},
 {'album_id': '45ozep8uHHnj5CCittuyXj',
  'name': "NewJeans 'OMG'",
  'release_date': '2023-01-02',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/45ozep8uHHnj5CCittuyXj'},
 {'album_id': '1kjfMVBNhsDeRyAu9zbLfF',
  'name': 'OzuTochi',
  'release_date': '2022-10-07',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/1kjfMVBNhsDeRyAu9zbLfF'},
 {'album_id': '493HYe7N5pleudEZRyhE7R',
  'name': 'All I Want Is You',
  'release_date': '2010-11-26',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/493HYe7N5pleudEZRyhE7R'},
 {'album_id': '7bnqo1fdJU9nSfXQd3bSMe',
  'name': 'Ditto',
  'release_date': '2022-12-19',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7bnqo1fdJU9nSfXQd3bSMe'},
 {'album_id': '4PNqWiJAfjj32hVvlchV5u',
  'name': 'Quevedo: Bzrp Music Sessions, Vol. 52',
  'release_date': '2022-07-06',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4PNqWiJAfjj32hVvlchV5u'},
 {'album_id': '69AaAkdktFGnk9POmHENkT',
  'name': 'this is what ____ feels like (Vol. 1-4)',
  'release_date': '2022-09-23',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/69AaAkdktFGnk9POmHENkT'},
 {'album_id': '04PEOM6kIEeq9lRp1asNP2',
  'name': 'I Ain’t Worried (Music From The Motion Picture "Top Gun: Maverick")',
  'release_date': '2022-05-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/04PEOM6kIEeq9lRp1asNP2'},
 {'album_id': '0KGBW1MQtC2aFPCDUdAkdJ',
  'name': 'Long Way Down',
  'release_date': '2013-06-17',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/0KGBW1MQtC2aFPCDUdAkdJ'},
 {'album_id': '2OXBosbXT7Qs3J6vBd6IkI',
  'name': 'PRC',
  'release_date': '2023-01-23',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2OXBosbXT7Qs3J6vBd6IkI'},
 {'album_id': '3z53jSP5i9bCPVOu3PARM8',
  'name': 'Love Again',
  'release_date': '2023-01-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3z53jSP5i9bCPVOu3PARM8'},
 {'album_id': '78bpIziExqiI9qztvNFlQu',
  'name': 'AM',
  'release_date': '2013-09-09',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/78bpIziExqiI9qztvNFlQu'},
 {'album_id': '5MS3MvWHJ3lOZPLiMxzOU6',
  'name': 'Her Loss',
  'release_date': '2022-11-04',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/5MS3MvWHJ3lOZPLiMxzOU6'},
 {'album_id': '0s2sLResjP92wRavoj9k0O',
  'name': 'AMG',
  'release_date': '2022-11-24',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0s2sLResjP92wRavoj9k0O'},
 {'album_id': '4LVa9bljQRvLYpWr8qyaXs',
  'name': "Takin' It Back",
  'release_date': '2022-10-21',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/4LVa9bljQRvLYpWr8qyaXs'},
 {'album_id': '3RQQmkQEvNCY4prGKE6oc5',
  'name': 'Un Verano Sin Ti',
  'release_date': '2022-05-06',
  'total_tracks': 23,
  'url': 'https://open.spotify.com/album/3RQQmkQEvNCY4prGKE6oc5'},
 {'album_id': '7ARtQpvnPN2ucbmVHngLOs',
  'name': 'Until I Found You (Em Beihold Version)',
  'release_date': '2022-04-22',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7ARtQpvnPN2ucbmVHngLOs'},
 {'album_id': '7JH7pr10sJV9caUhk3ORyK',
  'name': 'Sigan Hablando',
  'release_date': '2022-12-28',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/7JH7pr10sJV9caUhk3ORyK'},
 {'album_id': '6FJxoadUE4JNVwWHghBwnb',
  'name': 'RENAISSANCE',
  'release_date': '2022-07-29',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/6FJxoadUE4JNVwWHghBwnb'},
 {'album_id': '1kTlYbs28MXw7hwO0NLYif',
  'name': 'Encore (Deluxe Version)',
  'release_date': '2004-11-12',
  'total_tracks': 23,
  'url': 'https://open.spotify.com/album/1kTlYbs28MXw7hwO0NLYif'},
 {'album_id': '1skkjCQGfaGg0wpVw6cq5w',
  'name': 'X SI VOLVEMOS',
  'release_date': '2023-02-03',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1skkjCQGfaGg0wpVw6cq5w'},
 {'album_id': '7pijRxgRaBirPz6wDaJIp9',
  'name': 'FELIZ CUMPLEAÑOS FERXXO TE PIRATEAMOS EL ÁLBUM',
  'release_date': '2022-09-14',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/7pijRxgRaBirPz6wDaJIp9'},
 {'album_id': '7fOmdhRrRohTzToL617xkk',
  'name': '3 Songs At A Time Sampler',
  'release_date': '2023-01-31',
  'total_tracks': 3,
  'url': 'https://open.spotify.com/album/7fOmdhRrRohTzToL617xkk'},
 {'album_id': '6dj4bRg0LCMm7B2P5Xenq5',
  'name': 'Zona De Perigo',
  'release_date': '2022-12-08',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6dj4bRg0LCMm7B2P5Xenq5'},
 {'album_id': '07w0rG5TETcyihsEIZR3qG',
  'name': 'SOS',
  'release_date': '2022-12-09',
  'total_tracks': 23,
  'url': 'https://open.spotify.com/album/07w0rG5TETcyihsEIZR3qG'},
 {'album_id': '6yiXkzHvC0OTmhfDQOEWtS',
  'name': 'Mercury - Acts 1 & 2',
  'release_date': '2022-07-01',
  'total_tracks': 32,
  'url': 'https://open.spotify.com/album/6yiXkzHvC0OTmhfDQOEWtS'},
 {'album_id': '2ODvWsOgouMbaA5xf0RkJe',
  'name': 'Starboy',
  'release_date': '2016-11-25',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/2ODvWsOgouMbaA5xf0RkJe'},
 {'album_id': '2FD6g8bXEn2uQMYbeqqoCg',
  'name': 'Just Wanna Rock',
  'release_date': '2022-10-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2FD6g8bXEn2uQMYbeqqoCg'},
 {'album_id': '4B3FsNFguOEJ4TWEsct83B',
  'name': 'Romantic Homicide',
  'release_date': '2022-07-20',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4B3FsNFguOEJ4TWEsct83B'},
 {'album_id': '3Ks0eeH0GWpY4AU20D5HPD',
  'name': 'Gemini Rights',
  'release_date': '2022-07-15',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/3Ks0eeH0GWpY4AU20D5HPD'},
 {'album_id': '7txGsnDSqVMoRl6RQ9XyZP',
  'name': 'HEROES & VILLAINS',
  'release_date': '2022-12-02',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/7txGsnDSqVMoRl6RQ9XyZP'},
 {'album_id': '32G4vFNwLJQjpzkOoGEUUo',
  'name': 'Miss You',
  'release_date': '2022-08-05',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/32G4vFNwLJQjpzkOoGEUUo'},
 {'album_id': '3RQQmkQEvNCY4prGKE6oc5',
  'name': 'Un Verano Sin Ti',
  'release_date': '2022-05-06',
  'total_tracks': 23,
  'url': 'https://open.spotify.com/album/3RQQmkQEvNCY4prGKE6oc5'},
 {'album_id': '3okhA6w5uau6ZNhnVpwVww',
  'name': 'Indigo (Extended)',
  'release_date': '2019-10-04',
  'total_tracks': 42,
  'url': 'https://open.spotify.com/album/3okhA6w5uau6ZNhnVpwVww'},
 {'album_id': '156gxGFDxadwiIC3Bfwmj3',
  'name': 'DONDE QUIERO ESTAR',
  'release_date': '2023-01-20',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/156gxGFDxadwiIC3Bfwmj3'},
 {'album_id': '44mKxp7RB6x5O19VWqEXEm',
  'name': 'LLYLM',
  'release_date': '2023-01-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/44mKxp7RB6x5O19VWqEXEm'}]

In [70]:
data['items'][0]

{'added_at': '2023-02-10T09:38:05Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/'},
  'href': 'https://api.spotify.com/v1/users/',
  'id': '',
  'type': 'user',
  'uri': 'spotify:user:'},
 'is_local': False,
 'primary_color': None,
 'track': {'album': {'album_type': 'single',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6'},
     'href': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6',
     'id': '5YGY8feqx7naU7z4HrwZM6',
     'name': 'Miley Cyrus',
     'type': 'artist',
     'uri': 'spotify:artist:5YGY8feqx7naU7z4HrwZM6'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/7I0tjwFtxUwBC1vgyeMAax'},
   'href': 'https://api.spotify.com/v1/albums/7I0tjwFtxUwBC1vgyeMAax',
   'id': '7I0tjwFtxUwBC1vgyeMAax',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273f429549123dbe8552764ba1d',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02f429549123dbe8552764ba1d',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851f429549123dbe8552764ba1d',
     'width': 64}],
   'name': 'Flowers',
   'release_date': '2023-01-13',
   'release_date_precision': 'day',
   'total_tracks': 1,
   'type': 'album',
   'uri': 'spotify:album:7I0tjwFtxUwBC1vgyeMAax'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6'},
    'href': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6',
    'id': '5YGY8feqx7naU7z4HrwZM6',
    'name': 'Miley Cyrus',
    'type': 'artist',
    'uri': 'spotify:artist:5YGY8feqx7naU7z4HrwZM6'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 200454,
  'episode': False,
  'explicit': False,
  'external_ids': {'isrc': 'USSM12209777'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn'},
  'href': 'https://api.spotify.com/v1/tracks/0yLdNVWF3Srea0uzk55zFn',
  'id': '0yLdNVWF3Srea0uzk55zFn',
  'is_local': False,
  'name': 'Flowers',
  'popularity': 100,
  'preview_url': 'https://p.scdn.co/mp3-preview/f2857681239dee871da7055d2f725ea6dcd1b4d8?cid=cad932832b224420829e29749598ef3f',
  'track': True,
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:0yLdNVWF3Srea0uzk55zFn'},
 'video_thumbnail': {'url': None}}

In [75]:
artist_list = []
for row in data['items']:
    for key, value in row.items():
        if key == "track":
            for artist in value['artists']:
                artist_dict = {'artist_id':artist['id'], 'artist_name':artist['name'], 'external_url': artist['href']}
                artist_list.append(artist_dict)

In [76]:
artist_list

[{'artist_id': '5YGY8feqx7naU7z4HrwZM6',
  'artist_name': 'Miley Cyrus',
  'external_url': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6'},
 {'artist_id': '7tYKF4w9nC0nq9CsPZTHyP',
  'artist_name': 'SZA',
  'external_url': 'https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP'},
 {'artist_id': '716NhGYqD1jl2wI1Qkgq36',
  'artist_name': 'Bizarrap',
  'external_url': 'https://api.spotify.com/v1/artists/716NhGYqD1jl2wI1Qkgq36'},
 {'artist_id': '0EmeFodog0BfCgMzAIvKQp',
  'artist_name': 'Shakira',
  'external_url': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp'},
 {'artist_id': '2wY79sveU1sp5g7SokKOiI',
  'artist_name': 'Sam Smith',
  'external_url': 'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI'},
 {'artist_id': '3Xt3RrJMFv5SZkCfUE8C1J',
  'artist_name': 'Kim Petras',
  'external_url': 'https://api.spotify.com/v1/artists/3Xt3RrJMFv5SZkCfUE8C1J'},
 {'artist_id': '0iEtIxbK0KxaSlF7G42ZOp',
  'artist_name': 'Metro Boomin',
  'external_url': 'https://api.spotify.com/v1/artists/0iEtIxbK0KxaSlF7G42ZOp'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '6KImCVD70vtIoJWnq6nGn3',
  'artist_name': 'Harry Styles',
  'external_url': 'https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3'},
 {'artist_id': '0tmwSHipWxN12fsoLcFU3B',
  'artist_name': 'Manuel Turizo',
  'external_url': 'https://api.spotify.com/v1/artists/0tmwSHipWxN12fsoLcFU3B'},
 {'artist_id': '0eHQ9o50hj6ZDNBt6Ys1sD',
  'artist_name': 'Yandel',
  'external_url': 'https://api.spotify.com/v1/artists/0eHQ9o50hj6ZDNBt6Ys1sD'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '1Cs0zKBU1kc0i8ypK3B9ai',
  'artist_name': 'David Guetta',
  'external_url': 'https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai'},
 {'artist_id': '64M6ah0SkkRsnPGtGiRAbb',
  'artist_name': 'Bebe Rexha',
  'external_url': 'https://api.spotify.com/v1/artists/64M6ah0SkkRsnPGtGiRAbb'},
 {'artist_id': '5KKpBU5eC2tJDzf0wmlRp2',
  'artist_name': 'RAYE',
  'external_url': 'https://api.spotify.com/v1/artists/5KKpBU5eC2tJDzf0wmlRp2'},
 {'artist_id': '12Zk1DFhCbHY6v3xep2ZjI',
  'artist_name': '070 Shake',
  'external_url': 'https://api.spotify.com/v1/artists/12Zk1DFhCbHY6v3xep2ZjI'},
 {'artist_id': '46pWGuE3dSwY3bMMXGBvVS',
  'artist_name': 'Rema',
  'external_url': 'https://api.spotify.com/v1/artists/46pWGuE3dSwY3bMMXGBvVS'},
 {'artist_id': '0C8ZW7ezQVs4URX5aX7Kqx',
  'artist_name': 'Selena Gomez',
  'external_url': 'https://api.spotify.com/v1/artists/0C8ZW7ezQVs4URX5aX7Kqx'},
 {'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift',
  'external_url': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '4SsVbpTthjScTS7U2hmr1X',
  'artist_name': 'Arcángel',
  'external_url': 'https://api.spotify.com/v1/artists/4SsVbpTthjScTS7U2hmr1X'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '5y8tKLUfMvliMe8IKamR32',
  'artist_name': 'd4vd',
  'external_url': 'https://api.spotify.com/v1/artists/5y8tKLUfMvliMe8IKamR32'},
 {'artist_id': '6HvZYsbFfjnjFrWF950C9d',
  'artist_name': 'NewJeans',
  'external_url': 'https://api.spotify.com/v1/artists/6HvZYsbFfjnjFrWF950C9d'},
 {'artist_id': '1i8SpTcr7yvPOmcqrbnVXY',
  'artist_name': 'Ozuna',
  'external_url': 'https://api.spotify.com/v1/artists/1i8SpTcr7yvPOmcqrbnVXY'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '360IAlyVv4PCEVjgyMZrxK',
  'artist_name': 'Miguel',
  'external_url': 'https://api.spotify.com/v1/artists/360IAlyVv4PCEVjgyMZrxK'},
 {'artist_id': '6HvZYsbFfjnjFrWF950C9d',
  'artist_name': 'NewJeans',
  'external_url': 'https://api.spotify.com/v1/artists/6HvZYsbFfjnjFrWF950C9d'},
 {'artist_id': '716NhGYqD1jl2wI1Qkgq36',
  'artist_name': 'Bizarrap',
  'external_url': 'https://api.spotify.com/v1/artists/716NhGYqD1jl2wI1Qkgq36'},
 {'artist_id': '52iwsT98xCoGgiGntTiR7K',
  'artist_name': 'Quevedo',
  'external_url': 'https://api.spotify.com/v1/artists/52iwsT98xCoGgiGntTiR7K'},
 {'artist_id': '164Uj4eKjl6zTBKfJLFKKK',
  'artist_name': 'JVKE',
  'external_url': 'https://api.spotify.com/v1/artists/164Uj4eKjl6zTBKfJLFKKK'},
 {'artist_id': '5Pwc4xIPtQLFEnJriah9YJ',
  'artist_name': 'OneRepublic',
  'external_url': 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ'},
 {'artist_id': '2txHhyCwHjUEpJjWrEyqyX',
  'artist_name': 'Tom Odell',
  'external_url': 'https://api.spotify.com/v1/artists/2txHhyCwHjUEpJjWrEyqyX'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '0elWFr7TW8piilVRYJUe4P',
  'artist_name': 'Natanael Cano',
  'external_url': 'https://api.spotify.com/v1/artists/0elWFr7TW8piilVRYJUe4P'},
 {'artist_id': '2tIP7SsRs7vjIcLrU85W8J',
  'artist_name': 'The Kid LAROI',
  'external_url': 'https://api.spotify.com/v1/artists/2tIP7SsRs7vjIcLrU85W8J'},
 {'artist_id': '7Ln80lUS6He07XvHI8qqHH',
  'artist_name': 'Arctic Monkeys',
  'external_url': 'https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '0elWFr7TW8piilVRYJUe4P',
  'artist_name': 'Natanael Cano',
  'external_url': 'https://api.spotify.com/v1/artists/0elWFr7TW8piilVRYJUe4P'},
 {'artist_id': '12GqGscKJx3aE4t07u7eVZ',
  'artist_name': 'Peso Pluma',
  'external_url': 'https://api.spotify.com/v1/artists/12GqGscKJx3aE4t07u7eVZ'},
 {'artist_id': '6Sbl0NT50roqWvy746MfVf',
  'artist_name': 'Gabito Ballesteros',
  'external_url': 'https://api.spotify.com/v1/artists/6Sbl0NT50roqWvy746MfVf'},
 {'artist_id': '6JL8zeS1NmiOftqZTRgdTz',
  'artist_name': 'Meghan Trainor',
  'external_url': 'https://api.spotify.com/v1/artists/6JL8zeS1NmiOftqZTRgdTz'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '37230BxxYs9ksS7OkZw3IU',
  'artist_name': 'Chencho Corleone',
  'external_url': 'https://api.spotify.com/v1/artists/37230BxxYs9ksS7OkZw3IU'},
 {'artist_id': '5XKFrudbV4IiuE5WuTPRmT',
  'artist_name': 'Stephen Sanchez',
  'external_url': 'https://api.spotify.com/v1/artists/5XKFrudbV4IiuE5WuTPRmT'},
 {'artist_id': '7o2ZQYM7nTsaVdkXY38UAA',
  'artist_name': 'Em Beihold',
  'external_url': 'https://api.spotify.com/v1/artists/7o2ZQYM7nTsaVdkXY38UAA'},
 {'artist_id': '0ys2OFYzWYB5hRDLCsBqxt',
  'artist_name': 'Fuerza Regida',
  'external_url': 'https://api.spotify.com/v1/artists/0ys2OFYzWYB5hRDLCsBqxt'},
 {'artist_id': '6XkjpgcEsYab502Vr1bBeW',
  'artist_name': 'Grupo Frontera',
  'external_url': 'https://api.spotify.com/v1/artists/6XkjpgcEsYab502Vr1bBeW'},
 {'artist_id': '6vWDO969PvNqNYHIOW5v0m',
  'artist_name': 'Beyoncé',
  'external_url': 'https://api.spotify.com/v1/artists/6vWDO969PvNqNYHIOW5v0m'},
 {'artist_id': '7dGJo4pcD2V6oG8kP0tJRR',
  'artist_name': 'Eminem',
  'external_url': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR'},
 {'artist_id': '790FomKkXshlbRYZFtlgla',
  'artist_name': 'KAROL G',
  'external_url': 'https://api.spotify.com/v1/artists/790FomKkXshlbRYZFtlgla'},
 {'artist_id': '5lwmRuXgjX8xIwlnauTZIP',
  'artist_name': 'Romeo Santos',
  'external_url': 'https://api.spotify.com/v1/artists/5lwmRuXgjX8xIwlnauTZIP'},
 {'artist_id': '2LRoIwlKmHjgvigdNGBHNo',
  'artist_name': 'Feid',
  'external_url': 'https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo'},
 {'artist_id': '4oUHIQIBe0LHzYfvXNW4QM',
  'artist_name': 'Morgan Wallen',
  'external_url': 'https://api.spotify.com/v1/artists/4oUHIQIBe0LHzYfvXNW4QM'},
 {'artist_id': '7KVJCU4z5L4EUHILL8aMxR',
  'artist_name': 'Leo Santana',
  'external_url': 'https://api.spotify.com/v1/artists/7KVJCU4z5L4EUHILL8aMxR'},
 {'artist_id': '7tYKF4w9nC0nq9CsPZTHyP',
  'artist_name': 'SZA',
  'external_url': 'https://api.spotify.com/v1/artists/7tYKF4w9nC0nq9CsPZTHyP'},
 {'artist_id': '53XhwfbYqKCa1cC15pYq2q',
  'artist_name': 'Imagine Dragons',
  'external_url': 'https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'external_url': 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ'},
 {'artist_id': '4tZwfgrHOc3mvqYlEYSvVi',
  'artist_name': 'Daft Punk',
  'external_url': 'https://api.spotify.com/v1/artists/4tZwfgrHOc3mvqYlEYSvVi'},
 {'artist_id': '4O15NlyKLIASxsJ0PrXPfz',
  'artist_name': 'Lil Uzi Vert',
  'external_url': 'https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz'},
 {'artist_id': '5y8tKLUfMvliMe8IKamR32',
  'artist_name': 'd4vd',
  'external_url': 'https://api.spotify.com/v1/artists/5y8tKLUfMvliMe8IKamR32'},
 {'artist_id': '57vWImR43h4CaDao012Ofp',
  'artist_name': 'Steve Lacy',
  'external_url': 'https://api.spotify.com/v1/artists/57vWImR43h4CaDao012Ofp'},
 {'artist_id': '0iEtIxbK0KxaSlF7G42ZOp',
  'artist_name': 'Metro Boomin',
  'external_url': 'https://api.spotify.com/v1/artists/0iEtIxbK0KxaSlF7G42ZOp'},
 {'artist_id': '1RyvyyTE3xzB2ZywiAwp0i',
  'artist_name': 'Future',
  'external_url': 'https://api.spotify.com/v1/artists/1RyvyyTE3xzB2ZywiAwp0i'},
 {'artist_id': '7bXgB6jMjp9ATFy66eO08Z',
  'artist_name': 'Chris Brown',
  'external_url': 'https://api.spotify.com/v1/artists/7bXgB6jMjp9ATFy66eO08Z'},
 {'artist_id': '6TLwD7HPWuiOzvXEa3oCNe',
  'artist_name': 'Oliver Tree',
  'external_url': 'https://api.spotify.com/v1/artists/6TLwD7HPWuiOzvXEa3oCNe'},
 {'artist_id': '3t5xRXzsuZmMDkQzgOX35S',
  'artist_name': 'Robin Schulz',
  'external_url': 'https://api.spotify.com/v1/artists/3t5xRXzsuZmMDkQzgOX35S'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '7bXgB6jMjp9ATFy66eO08Z',
  'artist_name': 'Chris Brown',
  'external_url': 'https://api.spotify.com/v1/artists/7bXgB6jMjp9ATFy66eO08Z'},
 {'artist_id': '52iwsT98xCoGgiGntTiR7K',
  'artist_name': 'Quevedo',
  'external_url': 'https://api.spotify.com/v1/artists/52iwsT98xCoGgiGntTiR7K'},
 {'artist_id': '7ltDVBr6mKbRvohxheJ9h1',
  'artist_name': 'ROSALÍA',
  'external_url': 'https://api.spotify.com/v1/artists/7ltDVBr6mKbRvohxheJ9h1'}]

In [77]:
song_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added = row['added_at']
    album_id = row['track']['album']['id']
    artist_id = row['track']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [79]:
album_df = pd.DataFrame.from_dict(album_list)

In [80]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,7I0tjwFtxUwBC1vgyeMAax,Flowers,2023-01-13,1,https://open.spotify.com/album/7I0tjwFtxUwBC1v...
1,1nrVofqDRs7cpWXJ49qTnP,SOS,2022-12-08,23,https://open.spotify.com/album/1nrVofqDRs7cpWX...
2,1gi2iwr1l8IUyHYHxi01pg,"Shakira: Bzrp Music Sessions, Vol. 53",2023-01-11,1,https://open.spotify.com/album/1gi2iwr1l8IUyHY...
3,3Uq1jNGnD412ZvCb6j2DKV,Gloria,2023-01-27,13,https://open.spotify.com/album/3Uq1jNGnD412ZvC...
4,7txGsnDSqVMoRl6RQ9XyZP,HEROES & VILLAINS,2022-12-02,15,https://open.spotify.com/album/7txGsnDSqVMoRl6...

In [81]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      50 non-null     object
 1   name          50 non-null     object
 2   release_date  50 non-null     object
 3   total_tracks  50 non-null     int64
 4   url           50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [83]:
album_df = album_df.drop_duplicates(subset=['album_id'])

In [87]:
artist_df = pd.DataFrame.from_dict(artist_list)

In [89]:
artist_df = artist_df.drop_duplicates(subset=['artist_id'])

In [90]:
#Song Dataframe
song_df = pd.DataFrame.from_dict(song_list)

In [92]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,0yLdNVWF3Srea0uzk55zFn,Flowers,200454,https://open.spotify.com/track/0yLdNVWF3Srea0u...,100,2023-02-10T09:38:05Z,7I0tjwFtxUwBC1vgyeMAax,5YGY8feqx7naU7z4HrwZM6
1,1Qrg8KqiBpW07V7PNxwwwL,Kill Bill,153946,https://open.spotify.com/track/1Qrg8KqiBpW07V7...,91,2023-02-10T09:38:05Z,1nrVofqDRs7cpWXJ49qTnP,7tYKF4w9nC0nq9CsPZTHyP
2,4nrPB8O7Y7wsOCJdgXkthe,"Shakira: Bzrp Music Sessions, Vol. 53",214945,https://open.spotify.com/track/4nrPB8O7Y7wsOCJ...,96,2023-02-10T09:38:05Z,1gi2iwr1l8IUyHYHxi01pg,716NhGYqD1jl2wI1Qkgq36
3,0NZPBYD5qbEWRs3PrGiRkT,Unholy (feat. Kim Petras),156943,https://open.spotify.com/track/0NZPBYD5qbEWRs3...,82,2023-02-10T09:38:05Z,3Uq1jNGnD412ZvCb6j2DKV,2wY79sveU1sp5g7SokKOiI
4,2dHHgzDwk4BJdRwy9uXhTO,Creepin' (with The Weeknd & 21 Savage),221520,https://open.spotify.com/track/2dHHgzDwk4BJdRw...,93,2023-02-10T09:38:05Z,7txGsnDSqVMoRl6RQ9XyZP,0iEtIxbK0KxaSlF7G42ZOp

In [93]:
artist_df.head()

,artist_id,artist_name,external_url
0,5YGY8feqx7naU7z4HrwZM6,Miley Cyrus,https://api.spotify.com/v1/artists/5YGY8feqx7n...
1,7tYKF4w9nC0nq9CsPZTHyP,SZA,https://api.spotify.com/v1/artists/7tYKF4w9nC0...
2,716NhGYqD1jl2wI1Qkgq36,Bizarrap,https://api.spotify.com/v1/artists/716NhGYqD1j...
3,0EmeFodog0BfCgMzAIvKQp,Shakira,https://api.spotify.com/v1/artists/0EmeFodog0B...
4,2wY79sveU1sp5g7SokKOiI,Sam Smith,https://api.spotify.com/v1/artists/2wY79sveU1s...

In [94]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,7I0tjwFtxUwBC1vgyeMAax,Flowers,2023-01-13,1,https://open.spotify.com/album/7I0tjwFtxUwBC1v...
1,1nrVofqDRs7cpWXJ49qTnP,SOS,2022-12-08,23,https://open.spotify.com/album/1nrVofqDRs7cpWX...
2,1gi2iwr1l8IUyHYHxi01pg,"Shakira: Bzrp Music Sessions, Vol. 53",2023-01-11,1,https://open.spotify.com/album/1gi2iwr1l8IUyHY...
3,3Uq1jNGnD412ZvCb6j2DKV,Gloria,2023-01-27,13,https://open.spotify.com/album/3Uq1jNGnD412ZvC...
4,7txGsnDSqVMoRl6RQ9XyZP,HEROES & VILLAINS,2022-12-02,15,https://open.spotify.com/album/7txGsnDSqVMoRl6...

In [96]:
album_df['release_date'] = pd.to_datetime(album_df['release_date'])

In [98]:
song_df['song_added'] =  pd.to_datetime(song_df['song_added'])

In [100]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     object
 1   song_name    50 non-null     object
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     object
 4   popularity   50 non-null     int64
 5   song_added   50 non-null     datetime64[ns, UTC]
 6   album_id     50 non-null     object
 7   artist_id    50 non-null     object
dtypes: datetime64[ns, UTC](1), int64(2), object(5)
memory usage: 3.2+ KB